package main;

import java.awt.Color;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tx_destinatario = new javax.swing.JTextField();
        tx_nick = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tx_area = new javax.swing.JTextArea();
        bt_enviar = new javax.swing.JButton();
        tx_msg = new javax.swing.JTextField();
        bt_conectar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("NOME:");

        jLabel3.setText("DESTINATARIO:");

        tx_area.setEditable(false);
        tx_area.setBackground(new java.awt.Color(255, 255, 255));
        tx_area.setColumns(20);
        tx_area.setForeground(new java.awt.Color(0, 0, 0));
        tx_area.setRows(5);
        // tx_area.setText("===================================================\n                                                        MENSAGERIA\n===================================================\n########        ######    ########   |                FUMEC - FACE\n##             ##  ##         ##   ##            ## |--------------------------------------------------------  \n##             ##  ##                ##             ## | BRUNO PEREIRA LIMA | 219716404\n##             ##    ######    ##             ## | RAQUEL ZANINI          | 225533771\n##             ##                ##  ##             ## | RODRIGO LUIZ            | 220700941\n##             ##  ##         ##  ##             ## |--------------------------------------------------------\n########       ######    ########    | Prof.: Flávio Laper\n-------------------------------------------------------------------------------------------------------------------------------\n:::TRABALHO AUTOINSTRUCIONAL DESENVOLVIMENTO DE SISTEMAS DISTRIBUIDOS:::\n===================================================\n");
        jScrollPane1.setViewportView(tx_area);

        bt_enviar.setText("SEND");
        bt_enviar.setEnabled(false);
        bt_enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_enviar_click(evt);
            }
        });

        tx_msg.setEditable(false);
        tx_msg.setBackground(java.awt.Color.gray);

        bt_conectar.setText("Entrar");
        bt_conectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_connect_click(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tx_destinatario)
                            .addComponent(tx_nick)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                    .addComponent(tx_msg, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_enviar)
                        .addContainerGap())
                    .addComponent(bt_conectar, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx_nick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_conectar)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tx_destinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_enviar)
                    .addComponent(tx_msg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_enviar_click(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_enviar_click
        if(isConnected) {
            String destinatario = tx_destinatario.getText();
            if(!destinatario.isEmpty()) SetMensagem.enviaUnicast(
                      tx_nick.getText()
                              + ": " 
                              + (tx_msg.getText().isEmpty() 
                                      ? MsgPadrao.MENSAGEM_VAZIA 
                                      : tx_msg.getText())
                    , tx_nick.getText()
                    , destinatario);
            else SetMensagem.enviaBroadCast(
                      tx_nick.getText()
                              + ": " 
                              + (tx_msg.getText().isEmpty() 
                                      ? MsgPadrao.MENSAGEM_VAZIA 
                                      : tx_msg.getText())
                    , tx_nick.getText()
                    , StrProperty.ALL);
        }
        tx_msg.setText("");
    }//GEN-LAST:event_bt_enviar_click

    private void bt_connect_click(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_connect_click
        if(!isConnected){
            Random rand = new Random();
            rand.nextInt();
            if(tx_nick.getText().isEmpty()) tx_nick.setText(randomNames[rand.nextInt(20)]);
            getMensagem = new GetMensagem(tx_nick.getText(), this);
            bt_conectar.enableInputMethods(false);
            bt_conectar.setText(MsgPadrao.BT_DESCONECTAR);
            tx_nick.setEditable(false);
            tx_msg.setEditable(true);
            tx_nick.setBackground(Color.lightGray);
            tx_msg.setBackground(Color.WHITE);
            bt_enviar.setEnabled(true);
        } else {
            getMensagem.Dispose();
            bt_conectar.enableInputMethods(false);
            bt_conectar.setText(MsgPadrao.BT_CONECTAR);
            tx_nick.setEditable(true);
            tx_msg.setEditable(false);
            tx_nick.setBackground(Color.WHITE);
            tx_msg.setBackground(Color.lightGray);
            bt_enviar.setEnabled(false);
        }
        isConnected = !isConnected;
    }//GEN-LAST:event_bt_connect_click

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    private GetMensagem getMensagem = null;
    private boolean     isConnected = false;
    private String[]    randomNames = new String[]{
         "Abby"
        ,"Roxie"
        ,"Carissa"
        ,"Oliver"
        ,"Florence"
        ,"Alene"
        ,"Sheri"
        ,"Shasta"
        ,"Donetta"
        ,"Jeromy"
        ,"Sua Mae"
        ,"Melisa"
        ,"Cecila"
        ,"Darrel"  
        ,"Tad"
        ,"Jonathan"
        ,"Christiana"
        ,"Seema"
        ,"Domonique"  
        ,"Charlie"
    };
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_conectar;
    private javax.swing.JButton bt_enviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea tx_area;
    private javax.swing.JTextField tx_destinatario;
    private javax.swing.JTextField tx_msg;
    private javax.swing.JTextField tx_nick;
    // End of variables declaration//GEN-END:variables
}
